# Crash Course de Pandas: Manipulación y Análisis de Datos

Pandas es la biblioteca fundamental para el análisis de datos en Python. Proporciona estructuras de datos flexibles y de alto rendimiento, diseñadas para trabajar con datos tabulares y etiquetados de manera fácil e intuitiva.

En este notebook cubriremos las funcionalidades esenciales:
1. Creación y carga de datos
2. Inspección básica
3. Selección y filtrado
4. Limpieza de datos (Missing values)
5. Manipulación y transformación
6. Agrupación y agregación
7. Combinación de DataFrames

In [1]:
import pandas as pd
import numpy as np

## 1. Creación de Estructuras de Datos

Las dos estructuras principales en Pandas son:
*   **Series**: Un array unidimensional etiquetado (similar a una columna de Excel).
*   **DataFrame**: Una estructura tabular bidimensional (similar a una hoja de cálculo completa).

In [2]:
# Crear un DataFrame a partir de un diccionario
data = {
    'Nombre': ['Ana', 'Juan', 'Maria', 'Pedro', 'Sofia', 'Luis'],
    'Edad': [24, 30, 28, 35, 22, 40],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Madrid', 'Barcelona'],
    'Salario': [30000, 45000, 38000, 52000, 28000, 60000],
    'Departamento': ['RRHH', 'IT', 'Ventas', 'IT', 'Marketing', 'Dirección']
}

df = pd.DataFrame(data)
df

  Nombre  Edad     Ciudad  Salario Departamento
0    Ana    24     Madrid    30000         RRHH
1   Juan    30  Barcelona    45000           IT
2  Maria    28   Valencia    38000       Ventas
3  Pedro    35    Sevilla    52000           IT
4  Sofia    22     Madrid    28000    Marketing
5   Luis    40  Barcelona    60000    Dirección

## 2. Inspección de Datos

Antes de analizar, es crucial entender la estructura de nuestros datos.

In [3]:
# Ver las primeras filas
print("--- Head ---")
print(df.head(3))

# Información general (tipos de datos, memoria, valores no nulos)
print("\n--- Info ---")
df.info()

# Estadísticas descriptivas básicas
print("\n--- Describe ---")
print(df.describe())

# Dimensiones (filas, columnas)
print(f"\nDimensiones: {df.shape}")

--- Head ---
  Nombre  Edad     Ciudad  Salario Departamento
0    Ana    24     Madrid    30000         RRHH
1   Juan    30  Barcelona    45000           IT
2  Maria    28   Valencia    38000       Ventas

--- Info ---
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Nombre        6 non-null      str
 1   Edad          6 non-null      int64
 2   Ciudad        6 non-null      str
 3   Salario       6 non-null      int64
 4   Departamento  6 non-null      str
dtypes: int64(2), str(3)
memory usage: 476.0 bytes

--- Describe ---
            Edad       Salario
count   6.000000      6.000000
mean   29.833333  42166.666667
std     6.765107  12560.520159
min    22.000000  28000.000000
25%    25.000000  32000.000000
50%    29.000000  41500.000000
75%    33.750000  50250.000000
max    40.000000  60000.000000

Dimensiones: (6, 5)

## 3. Selección y Filtrado

Pandas ofrece múltiples formas de seleccionar datos: por etiqueta (`loc`), por posición (`iloc`) o usando lógica booleana.

In [4]:
# Selección de una columna (devuelve una Series)
print(df['Nombre'])

# Selección de múltiples columnas (devuelve un DataFrame)
subset = df[['Nombre', 'Salario']]
subset.head(2)

0      Ana
1     Juan
2    Maria
3    Pedro
4    Sofia
5     Luis
Name: Nombre, dtype: str

  Nombre  Salario
0    Ana    30000
1   Juan    45000

In [5]:
# Filtrado condicional: Personas mayores de 25 años
mayores_25 = df[df['Edad'] > 25]
mayores_25

  Nombre  Edad     Ciudad  Salario Departamento
1   Juan    30  Barcelona    45000           IT
2  Maria    28   Valencia    38000       Ventas
3  Pedro    35    Sevilla    52000           IT
5   Luis    40  Barcelona    60000    Dirección

In [6]:
# Filtrado con múltiples condiciones (AND '&', OR '|')
# Empleados de IT con salario mayor a 40000
filtro_it = df[(df['Departamento'] == 'IT') & (df['Salario'] > 40000)]
filtro_it

  Nombre  Edad     Ciudad  Salario Departamento
1   Juan    30  Barcelona    45000           IT
3  Pedro    35    Sevilla    52000           IT

In [7]:
# .loc (basado en etiquetas/nombres)
# Seleccionar filas donde la Ciudad es Madrid y solo columna Salario
print(df.loc[df['Ciudad'] == 'Madrid', 'Salario'])

# .iloc (basado en índices numéricos)
# Seleccionar filas 0 a 2 y columnas 0 a 2
print("\nSubselección por posición:")
print(df.iloc[0:3, 0:3])

0    30000
4    28000
Name: Salario, dtype: int64

Subselección por posición:
  Nombre  Edad     Ciudad
0    Ana    24     Madrid
1   Juan    30  Barcelona
2  Maria    28   Valencia

## 4. Manipulación y Columnas Nuevas

Podemos crear nuevas variables a partir de las existentes o modificar las actuales.

In [8]:
# Crear una nueva columna calculada
df['Salario_Mensual'] = df['Salario'] / 12

# Aplicar una función a una columna
df['Nombre_Mayus'] = df['Nombre'].apply(lambda x: x.upper())

df.head()

  Nombre  Edad     Ciudad  Salario Departamento  Salario_Mensual Nombre_Mayus
0    Ana    24     Madrid    30000         RRHH      2500.000000          ANA
1   Juan    30  Barcelona    45000           IT      3750.000000         JUAN
2  Maria    28   Valencia    38000       Ventas      3166.666667        MARIA
3  Pedro    35    Sevilla    52000           IT      4333.333333        PEDRO
4  Sofia    22     Madrid    28000    Marketing      2333.333333        SOFIA

## 5. Manejo de Datos Faltantes (NaN)

Los datos del mundo real suelen estar incompletos.

In [9]:
# Introducimos algunos valores nulos para el ejemplo
df_nan = df.copy()
df_nan.loc[0, 'Salario'] = np.nan
df_nan.loc[2, 'Ciudad'] = np.nan

print("DataFrame con nulos:")
print(df_nan)

# Detectar nulos
print("\nConteo de nulos por columna:")
print(df_nan.isna().sum())

DataFrame con nulos:
  Nombre  Edad     Ciudad  Salario Departamento  Salario_Mensual Nombre_Mayus
0    Ana    24     Madrid      NaN         RRHH      2500.000000          ANA
1   Juan    30  Barcelona  45000.0           IT      3750.000000         JUAN
2  Maria    28        NaN  38000.0       Ventas      3166.666667        MARIA
3  Pedro    35    Sevilla  52000.0           IT      4333.333333        PEDRO
4  Sofia    22     Madrid  28000.0    Marketing      2333.333333        SOFIA
5   Luis    40  Barcelona  60000.0    Dirección      5000.000000         LUIS

Conteo de nulos por columna:
Nombre             0
Edad               0
Ciudad             1
Salario            1
Departamento       0
Salario_Mensual    0
Nombre_Mayus       0
dtype: int64

In [10]:
# Opción A: Llenar nulos (Imputación)
# Llenar salario con la media
media_salario = df_nan['Salario'].mean()
df_lleno = df_nan.fillna({'Salario': media_salario, 'Ciudad': 'Desconocido'})

# Opción B: Eliminar filas con nulos
df_limpio = df_nan.dropna()

print("DataFrame después de eliminar nulos:")
print(df_limpio)

DataFrame después de eliminar nulos:
  Nombre  Edad     Ciudad  Salario Departamento  Salario_Mensual Nombre_Mayus
1   Juan    30  Barcelona  45000.0           IT      3750.000000         JUAN
3  Pedro    35    Sevilla  52000.0           IT      4333.333333        PEDRO
4  Sofia    22     Madrid  28000.0    Marketing      2333.333333        SOFIA
5   Luis    40  Barcelona  60000.0    Dirección      5000.000000         LUIS

## 6. Agrupación y Agregación (Groupby)

El método `groupby` es esencial para el análisis "split-apply-combine". Permite agrupar datos por categorías y calcular estadísticas.

In [11]:
# Salario medio por Departamento
salario_por_depto = df.groupby('Departamento')['Salario'].mean().sort_values(ascending=False)
print(salario_por_depto)

Departamento
Dirección    60000.0
IT           48500.0
Ventas       38000.0
RRHH         30000.0
Marketing    28000.0
Name: Salario, dtype: float64

In [12]:
# Múltiples agregaciones
resumen = df.groupby('Ciudad').agg({
    'Salario': ['mean', 'min', 'max'],
    'Edad': 'mean',
    'Nombre': 'count' # conteo de personas
})
resumen

           Salario                Edad Nombre
              mean    min    max  mean  count
Ciudad
Barcelona  52500.0  45000  60000  35.0      2
Madrid     29000.0  28000  30000  23.0      2
Sevilla    52000.0  52000  52000  35.0      1
Valencia   38000.0  38000  38000  28.0      1

## 7. Ordenar y Valores Únicos

In [13]:
# Ordenar por Salario descendente
df_ordenado = df.sort_values(by='Salario', ascending=False)

# Valores únicos en una columna
ciudades_unicas = df['Ciudad'].unique()

print(f"Ciudades presentes: {ciudades_unicas}")
df_ordenado.head(3)

Ciudades presentes: <ArrowStringArray>
['Madrid', 'Barcelona', 'Valencia', 'Sevilla']
Length: 4, dtype: str

  Nombre  Edad     Ciudad  Salario Departamento  Salario_Mensual Nombre_Mayus
5   Luis    40  Barcelona    60000    Dirección      5000.000000         LUIS
3  Pedro    35    Sevilla    52000           IT      4333.333333        PEDRO
1   Juan    30  Barcelona    45000           IT      3750.000000         JUAN

## Conclusión

Pandas es una herramienta muy extensa. Este "crash course" cubre el 80% de los casos de uso diarios: cargar, limpiar, filtrar y agregar datos. 

Siguientes pasos recomendados:
*   Profundizar en `merge` y `concat` para unir tablas.
*   Explorar el manejo de series temporales (`pd.to_datetime`).
*   Practicar con visualizaciones básicas integradas (`df.plot()`).